---
title: "Shiny App"
output: html_document
https://www.kaggle.com/dorbicycle/world-foodfeed-production/home
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load libraries
```{r libraries}
library(tidyr)
library(devtools)
library(DataExplorer)
library(rvest)
library(dplyr)
library(lubridate)
library(stringr)
library(readr)
library(timeDate)
library(shiny)
library(plotly)
library(ggplot2)
library(Hmisc)
library(microbenchmark)
library(knitr)
library(shinythemes)
library(shinyWidgets)
library(rgdal)
```


#Import Data
```{r import data}
# UN food production data
data <- read_csv('C:/Users/BieniekJon/Desktop/901/R/Shiny/FAO.csv')
print(data)
# UN countries by region
region <- read_csv('C:/Users/BieniekJon/Desktop/901/R/Shiny/Region list.csv')
print(region)
# Food categories
categories <- read_csv('C:/Users/BieniekJon/Desktop/901/R/Shiny/Food Categories.csv')
print(categories)
```

# Use left join to add region and food categories to the UN data set
```{r join data}
joined_data <- left_join(data,region,by = c("Area" = "Country"))
print(joined_data)

joined_data2 <- left_join(joined_data,categories,by = c("Item" = "Items"))
print(joined_data2)
```

Remove and row with an NA
```{r remove NAs}
no_na <- joined_data2[complete.cases(joined_data2),]
no_na[is.na(no_na$`Food_Sub_Category`),]
```

Subset the data
```{r}
columns_of_interest <- c("Element","Area","Region","Food_Sub_Category", "Y1961", "Y1962", "Y1963", "Y1964", "Y1965", "Y1966","Y1967","Y1968","Y1969","Y1970","Y1971","Y1972","Y1973","Y1974","Y1975","Y1976","Y1977","Y1978","Y1979","Y1980","Y1981","Y1982","Y1983","Y1984","Y1985","Y1986","Y1987","Y1988","Y1989","Y1990","Y1991","Y1992","Y1993","Y1994","Y1995","Y1996","Y1997","Y1998","Y1999","Y2000","Y2001","Y2002","Y2003","Y2004","Y2005","Y2006","Y2007","Y2008","Y2009","Y2010","Y2011","Y2012","Y2013")
data_subset <- no_na[columns_of_interest]
print(data_subset)
data_subset[is.na(data_subset),]
```

# Create a flat file using the gather() function.
```{r flat_file}
flat_file <- gather(data_subset, "Year", "Prod_one_tho_ton", 5:57)
print(flat_file)
```

Remove the letter Y from Year elements
```{r remove letter from string}

flat_file$Year <- gsub("Y", "",flat_file$Year)
print(flat_file)
```
```{r}
flat_file2 <- flat_file
flat_file2
```

```{r}
flat_file[flatfile]
```

Transform all columns except the Production column into factors. This will make ploting graphs easier.
```{r turn to factors}
flat_file$Element <- as.factor(flat_file$Element)
flat_file$Area <- as.factor(flat_file$Area)
flat_file$Region <- as.factor(flat_file$Region)
flat_file$Food_Sub_Category <- as.factor(flat_file$Food_Sub_Category)
flat_file$Year <- as.factor(flat_file$Year)
```




Shiny App

Variables for shiny
```{r shiny variables}
regions <- unique(flat_file$Region)
food_cat <- unique(flat_file$Food_Sub_Category)
countries <- unique(flat_file2$Area)
```

Shiny code
```{r}
# Define UI for application that plots features of movies
ui <- shinyUI(
    navbarPage("Page Title",
               tabPanel("Panel 1",
  
  # Sidebar layout with a input and output definitions
  sidebarLayout(
    
    # Inputs
    sidebarPanel(
        tags$h3("List of Input"),
        radioButtons(inputId = "purpose", 
                     label = "Intended use of Goods Produced", 
                     choices =c("Human Consumption" = "Food",
                                "Animal Consumption" = "Feed"),
                     selected = "Food"),
        
        pickerInput(inputId = "region",
                    label = "Global Region:",
                    choices = regions,
                    options = list(`actions-box` = TRUE),
                    multiple = TRUE),
        
        pickerInput(inputId = "group",
                    label = "Food Category:",
                    choices = food_cat,
                    options = list(`actions-box` = TRUE),
                    multiple = TRUE)
                  ),
      
      # Outputs
      mainPanel(
        tabsetPanel(
          tabPanel("Bar Plot",
                   h2("Total Production"),
                   plotlyOutput(outputId = "barplot")),
          tabPanel("Data Table",
                  h2("Data Table"),
                  dataTableOutput(outputId = "table")
                    )
                  )
                )
              )
            ),
  
                tabPanel("Panel 2",
  
  # Sidebar layout with a input and output definitions
  sidebarLayout(
    
    # Inputs
    sidebarPanel(
        tags$h3("List of Input"),
        radioButtons(inputId = "purpose2", 
                     label = "Intended use of Goods Produced", 
                     choices =c("Human Consumption" = "Food",
                                "Animal Consumption" = "Feed"),
                     selected = "Food"),
        
        pickerInput(inputId = "group2",
                    label = "Food Category:",
                    choices = food_cat,
                    options = list(`actions-box` = TRUE),
                    multiple = TRUE),
        
        pickerInput(inputId = "region2",
                    label = "Global Region:",
                    choices = regions,
                    options = list(`actions-box` = TRUE),
                    multiple = TRUE),
        
        pickerInput(inputId = "country",
                    label = "Country:",
                    choices = countries,
                    options = list(`actions-box` = TRUE),
                    multiple = TRUE)
                  ),
      
      # Outputs
      mainPanel(
        tabsetPanel(
          tabPanel("Bar Plot",
                   h2("Total Production"),
                   plotlyOutput(outputId = "barplot2")),
          tabPanel("Data Table",
                  h2("Data Table"),
                  dataTableOutput(outputId = "table2")
                   )
                    )
                )
              )
            )
    )
)
# Define server function required to create the scatterplot
server <- function(input, output,session) {
### Tab 1
      filtered_data <- reactive({filter(flat_file, Element == input$purpose)})
      observe({
                updateSelectInput(session,"region", choices = unique(filtered_data()$Region))
      })
      
      filtered_data_2 <- reactive({filter(filtered_data(), Region %in% input$region)})
      observe({
                updateSelectInput(session,"group", choices = unique(filtered_data_2()$Food_Sub_Category))
      })
      filtered_data_3 <- reactive({filter(filtered_data_2(),Food_Sub_Category %in% input$group)})

# Create scatterplot
      output$barplot <- renderPlotly(
     {
          p<-ggplot(filtered_data_3(), aes(Year, weight=Prod_one_tho_ton)) + geom_bar()
          ggplotly(p)   
   }
   )
      
     output$barplot2 <- renderPlotly(
     {
          p<-ggplot(filtered_data_7(), aes(Year, weight=Prod_one_tho_ton)) + geom_bar()
          ggplotly(p)   
   }
   ) 
#### Tab 2      
      filtered_data_4 <- reactive({filter(flat_file2, Element ==input$purpose2)})
      observe({
                updateSelectInput(session,"group2", choices = unique(filtered_data_4()$Food_Sub_Category))
      })
      
      filtered_data_5 <- reactive({filter(filtered_data_4(), Food_Sub_Category %in% input$group2)})
      observe({
                updateSelectInput(session,"region2", choices = unique(filtered_data_5()$Region))
      })
      
       filtered_data_6 <- reactive({filter(filtered_data_5(), Region %in% input$region2)})
      observe({
                updateSelectInput(session,"country", choices = unique(filtered_data_6()$Area))
      })
      
      filtered_data_7 <- reactive({filter(filtered_data_6(),Area %in% input$country)}) 
      
}

# Create the Shiny app object
shinyApp(ui, server)
```
   